//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de.janhendrikpeters.helpdesk.toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("de.janhendrikpeters.helpdesk.toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event logs.
        /// </summary>
        public static string Action_EventLogs {
            get {
                return ResourceManager.GetString("Action_EventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string Action_Processes {
            get {
                return ResourceManager.GetString("Action_Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot status.
        /// </summary>
        public static string Action_RebootStatus {
            get {
                return ResourceManager.GetString("Action_RebootStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Action_Services {
            get {
                return ResourceManager.GetString("Action_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed software.
        /// </summary>
        public static string Action_Software {
            get {
                return ResourceManager.GetString("Action_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Action_Tasks {
            get {
                return ResourceManager.GetString("Action_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop process(es).
        /// </summary>
        public static string ButtonKillProcesses {
            get {
                return ResourceManager.GetString("ButtonKillProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart service.
        /// </summary>
        public static string ButtonRestartService {
            get {
                return ResourceManager.GetString("ButtonRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start service.
        /// </summary>
        public static string ButtonStartService {
            get {
                return ResourceManager.GetString("ButtonStartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start task.
        /// </summary>
        public static string ButtonStartTask {
            get {
                return ResourceManager.GetString("ButtonStartTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop service.
        /// </summary>
        public static string ButtonStopService {
            get {
                return ResourceManager.GetString("ButtonStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop task.
        /// </summary>
        public static string ButtonStopTask {
            get {
                return ResourceManager.GetString("ButtonStopTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        ///Attempted operation: {0}, exception message: {1}.
        /// </summary>
        public static string Error_GenericError {
            get {
                return ResourceManager.GetString("Error_GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the necessary permissions to perform this operation.
        ///Attempted operation: {0}, exception message: {1}.
        /// </summary>
        public static string Error_InsufficientPermissions {
            get {
                return ResourceManager.GetString("Error_InsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error looking for organizational units.
        ///.
        /// </summary>
        public static string Error_OUSearch {
            get {
                return ResourceManager.GetString("Error_OUSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error searching for stores.
        ///.
        /// </summary>
        public static string Error_StoreSearch {
            get {
                return ResourceManager.GetString("Error_StoreSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Generic_Error {
            get {
                return ResourceManager.GetString("Generic_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available, Not Available.
        /// </summary>
        public static string Label_AvailableNotAvailable {
            get {
                return ResourceManager.GetString("Label_AvailableNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is component-based servicing reboot:.
        /// </summary>
        public static string Label_IsCcmReboot {
            get {
                return ResourceManager.GetString("Label_IsCcmReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Windows update Reboot:.
        /// </summary>
        public static string Label_IsWuauReboot {
            get {
                return ResourceManager.GetString("Label_IsWuauReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending file renames:.
        /// </summary>
        public static string Label_PendingFileRenames {
            get {
                return ResourceManager.GetString("Label_PendingFileRenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot pending:.
        /// </summary>
        public static string Label_RebootIsPending {
            get {
                return ResourceManager.GetString("Label_RebootIsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable machines.
        /// </summary>
        public static string Label_UnavailableMachines {
            get {
                return ResourceManager.GetString("Label_UnavailableMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter expression.
        /// </summary>
        public static string LabelFilterExpression {
            get {
                return ResourceManager.GetString("LabelFilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot status: nA.
        /// </summary>
        public static string LabelRebootStatus {
            get {
                return ResourceManager.GetString("LabelRebootStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} No pending reboots.
        /// </summary>
        public static string LabelRebootStatusOk {
            get {
                return ResourceManager.GetString("LabelRebootStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Reboot pending.
        /// </summary>
        public static string LabelRebootStatusPending {
            get {
                return ResourceManager.GetString("LabelRebootStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting orders....
        /// </summary>
        public static string LabelStatusInfo_ContentStandard {
            get {
                return ResourceManager.GetString("LabelStatusInfo_ContentStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuItemFile {
            get {
                return ResourceManager.GetString("MenuItemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItemHelp {
            get {
                return ResourceManager.GetString("MenuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reload servers.
        /// </summary>
        public static string MenuItemReload {
            get {
                return ResourceManager.GetString("MenuItemReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open status window.
        /// </summary>
        public static string MenuItemShowStatusWindow {
            get {
                return ResourceManager.GetString("MenuItemShowStatusWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string String_AboutCaption {
            get {
                return ResourceManager.GetString("String_AboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Jan-Hendrik Peters
        ///Version: {0}
        ///Compilation date: {1}.
        /// </summary>
        public static string String_AboutText {
            get {
                return ResourceManager.GetString("String_AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected processes killed.
        /// </summary>
        public static string String_AllProcessesKilled {
            get {
                return ResourceManager.GetString("String_AllProcessesKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected services restarted.
        /// </summary>
        public static string String_AllServicesRestarted {
            get {
                return ResourceManager.GetString("String_AllServicesRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected services started.
        /// </summary>
        public static string String_AllServicesStarted {
            get {
                return ResourceManager.GetString("String_AllServicesStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected services stopped.
        /// </summary>
        public static string String_AllServicesStopped {
            get {
                return ResourceManager.GetString("String_AllServicesStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Error.
        /// </summary>
        public static string String_AppError {
            get {
                return ResourceManager.GetString("String_AppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string String_Availability {
            get {
                return ResourceManager.GetString("String_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available machines.
        /// </summary>
        public static string String_AvailableMachines {
            get {
                return ResourceManager.GetString("String_AvailableMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers available.
        /// </summary>
        public static string String_AvailableServers {
            get {
                return ResourceManager.GetString("String_AvailableServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/restart/stop service on multiple machines.
        /// </summary>
        public static string String_ChangeServiceOnMultipleMachines {
            get {
                return ResourceManager.GetString("String_ChangeServiceOnMultipleMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable task.
        /// </summary>
        public static string String_DisableTask {
            get {
                return ResourceManager.GetString("String_DisableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error disabling task {0}. Exception was {1}.
        /// </summary>
        public static string String_DisableTasksError {
            get {
                return ResourceManager.GetString("String_DisableTasksError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling {0} tasks.
        /// </summary>
        public static string String_DisablingTasks {
            get {
                return ResourceManager.GetString("String_DisablingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable task.
        /// </summary>
        public static string String_EnableTask {
            get {
                return ResourceManager.GetString("String_EnableTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling {0} tasks.
        /// </summary>
        public static string String_EnablingTasks {
            get {
                return ResourceManager.GetString("String_EnablingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a process name before killing it..
        /// </summary>
        public static string String_EnterProcessBeforeKill {
            get {
                return ResourceManager.GetString("String_EnterProcessBeforeKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error enabling task {0}. Exception was {1}.
        /// </summary>
        public static string String_ErrorEnablingTasks {
            get {
                return ResourceManager.GetString("String_ErrorEnablingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application error occurred.
        ///Please check whether your data is correct and repeat the action. If this error occurs again there seems to be a more serious malfunction in the application, and you better close it.
        ///
        ///Error:
        ///{0}
        ///
        ///Do you want to continue?
        ///(if you click Yes you will continue with your work, if you click No the application will close)
        ///
        ///.
        /// </summary>
        public static string String_ErrorMessageBox {
            get {
                return ResourceManager.GetString("String_ErrorMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event logs retrieved from {0}.
        /// </summary>
        public static string String_EventLogsRetrieved {
            get {
                return ResourceManager.GetString("String_EventLogsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method name: {0}
        ///.
        /// </summary>
        public static string String_ExceptionMethod {
            get {
                return ResourceManager.GetString("String_ExceptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurence: Line {0}, character {1}
        ///.
        /// </summary>
        public static string String_ExceptionOccurrence {
            get {
                return ResourceManager.GetString("String_ExceptionOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file: {0}
        ///.
        /// </summary>
        public static string String_ExceptionSource {
            get {
                return ResourceManager.GetString("String_ExceptionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this function is currently not fully working..
        /// </summary>
        public static string String_FunctionNotImplemented {
            get {
                return ResourceManager.GetString("String_FunctionNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing processes on {0}.
        /// </summary>
        public static string String_KillingProcesses {
            get {
                return ResourceManager.GetString("String_KillingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill process on multiple machines.
        /// </summary>
        public static string String_KillProcOnMachines {
            get {
                return ResourceManager.GetString("String_KillProcOnMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot status.
        /// </summary>
        public static string String_RebootStatus {
            get {
                return ResourceManager.GetString("String_RebootStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh in {0}.
        /// </summary>
        public static string String_Refresh {
            get {
                return ResourceManager.GetString("String_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting service {0}.
        /// </summary>
        public static string String_RestartingService {
            get {
                return ResourceManager.GetString("String_RestartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving event log names for {0}.
        /// </summary>
        public static string String_RetrieveEventLogs {
            get {
                return ResourceManager.GetString("String_RetrieveEventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving installed software for {0}.
        /// </summary>
        public static string String_RetrieveInstalledSoftware {
            get {
                return ResourceManager.GetString("String_RetrieveInstalledSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving processes for {0}.
        /// </summary>
        public static string String_RetrieveProcesses {
            get {
                return ResourceManager.GetString("String_RetrieveProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving reboot status for {0}.
        /// </summary>
        public static string String_RetrieveRebootStatus {
            get {
                return ResourceManager.GetString("String_RetrieveRebootStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving services for {0}.
        /// </summary>
        public static string String_RetrieveServices {
            get {
                return ResourceManager.GetString("String_RetrieveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving scheduled tasks for {0}.
        /// </summary>
        public static string String_RetrieveTasks {
            get {
                return ResourceManager.GetString("String_RetrieveTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving warnings and errors from log {0}.
        /// </summary>
        public static string String_RetrievingEvents {
            get {
                return ResourceManager.GetString("String_RetrievingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string String_Server {
            get {
                return ResourceManager.GetString("String_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service {0}.
        /// </summary>
        public static string String_StartingService {
            get {
                return ResourceManager.GetString("String_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0} tasks..
        /// </summary>
        public static string String_StartingTasks {
            get {
                return ResourceManager.GetString("String_StartingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string String_Status {
            get {
                return ResourceManager.GetString("String_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability overview.
        /// </summary>
        public static string String_StatusWindow {
            get {
                return ResourceManager.GetString("String_StatusWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service {0}.
        /// </summary>
        public static string String_StoppingService {
            get {
                return ResourceManager.GetString("String_StoppingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0} tasks..
        /// </summary>
        public static string String_StoppingTasks {
            get {
                return ResourceManager.GetString("String_StoppingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled {0} tasks..
        /// </summary>
        public static string String_TasksDisabled {
            get {
                return ResourceManager.GetString("String_TasksDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled {0} tasks..
        /// </summary>
        public static string String_TasksEnabled {
            get {
                return ResourceManager.GetString("String_TasksEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started {0} tasks..
        /// </summary>
        public static string String_TasksStarted {
            get {
                return ResourceManager.GetString("String_TasksStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped {0} tasks..
        /// </summary>
        public static string String_TasksStopped {
            get {
                return ResourceManager.GetString("String_TasksStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting task {0}. Exception was {1}.
        /// </summary>
        public static string String_TaskStartError {
            get {
                return ResourceManager.GetString("String_TaskStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping task {0}. Exception was {1}.
        /// </summary>
        public static string String_TaskStopError {
            get {
                return ResourceManager.GetString("String_TaskStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event log.
        /// </summary>
        public static string TabItemEventLog {
            get {
                return ResourceManager.GetString("TabItemEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed software.
        /// </summary>
        public static string TabItemInstalledSoftware {
            get {
                return ResourceManager.GetString("TabItemInstalledSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string TabItemProcesses {
            get {
                return ResourceManager.GetString("TabItemProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled tasks.
        /// </summary>
        public static string TabItemScheduledTask {
            get {
                return ResourceManager.GetString("TabItemScheduledTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string TabItemServices {
            get {
                return ResourceManager.GetString("TabItemServices", resourceCulture);
            }
        }
    }
}
